from create_team import Ui_MainWindow as CreateTeam
from open_team import Ui_MainWindow as OpenTeam
from evaluate_team import Ui_TeamBox as EvaluateTeam
from PyQt5 import QtCore, QtGui, QtWidgets 
#from PyQt5.QtWidgets import QMessagebox
import sqlite3
connect = sqlite3.connect('fantasy.db')
curfantasy = connect.cursor()


class Ui_MainWindow(object):
    def __init__(self):
        self.max_WK = 1
        self.create_team = QtWidgets.QMainWindow()
        self.create_screen = CreateTeam()
        self.create_screen.setupUi(self.create_team)
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(29, 240, 741, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list1 = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.list1.setObjectName("list1")
        self.horizontalLayout.addWidget(self.list1)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.list2 = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.list2.setObjectName("list2")
        self.horizontalLayout.addWidget(self.list2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 100, 751, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bat = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.bat.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.bat.setFont(font)
        self.bat.setObjectName("bat")
        self.horizontalLayout_2.addWidget(self.bat)
        self.bowl = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.bowl.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.bowl.setFont(font)
        self.bowl.setObjectName("bowl")
        self.horizontalLayout_2.addWidget(self.bowl)
        self.AR = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.AR.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.AR.setFont(font)
        self.AR.setObjectName("AR")
        self.horizontalLayout_2.addWidget(self.AR)
        self.wk = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.wk.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.wk.setFont(font)
        self.wk.setObjectName("wk")
        self.horizontalLayout_2.addWidget(self.wk)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 796, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.batsman_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.batsman_1.setFont(font)
        self.batsman_1.setObjectName("batsman_1")
        self.horizontalLayout_3.addWidget(self.batsman_1)
        self.batsman_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.batsman_2.setFont(font)
        self.batsman_2.setObjectName("batsman_2")
        self.horizontalLayout_3.addWidget(self.batsman_2)
        self.Bowler_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Bowler_1.setFont(font)
        self.Bowler_1.setObjectName("Bowler_1")
        self.horizontalLayout_3.addWidget(self.Bowler_1)
        self.Bowler_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Bowler_2.setFont(font)
        self.Bowler_2.setObjectName("Bowler_2")
        self.horizontalLayout_3.addWidget(self.Bowler_2)
        self.AllRounder_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.AllRounder_1.setFont(font)
        self.AllRounder_1.setObjectName("AllRounder_1")
        self.horizontalLayout_3.addWidget(self.AllRounder_1)
        self.AllRounder_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.AllRounder_2.setFont(font)
        self.AllRounder_2.setObjectName("AllRounder_2")
        self.horizontalLayout_3.addWidget(self.AllRounder_2)
        self.WicketKeeper_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.WicketKeeper_1.setFont(font)
        self.WicketKeeper_1.setObjectName("WicketKeeper_1")
        self.horizontalLayout_3.addWidget(self.WicketKeeper_1)
        self.WicketKeeper_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.WicketKeeper_2.setFont(font)
        self.WicketKeeper_2.setObjectName("WicketKeeper_2")
        self.horizontalLayout_3.addWidget(self.WicketKeeper_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 801, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PointsAvailableText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.PointsAvailableText.setFont(font)
        self.PointsAvailableText.setObjectName("PointsAvailableText")
        self.horizontalLayout_4.addWidget(self.PointsAvailableText)
        self.PointsAvailableBox = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.PointsAvailableBox.setFont(font)
        self.PointsAvailableBox.setObjectName("PointsAvailableBox")
        self.horizontalLayout_4.addWidget(self.PointsAvailableBox)
        self.TeamNameText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.TeamNameText.setFont(font)
        self.TeamNameText.setObjectName("TeamNameText")
        self.horizontalLayout_4.addWidget(self.TeamNameText)
        self.TeamNameBox = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.TeamNameBox.setFont(font)
        self.TeamNameBox.setObjectName("TeamNameBox")
        self.horizontalLayout_4.addWidget(self.TeamNameBox)
        self.PointUsedText = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.PointUsedText.setFont(font)
        self.PointUsedText.setObjectName("PointUsedText")
        self.horizontalLayout_4.addWidget(self.PointUsedText)
        self.PointUsedBox = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.PointUsedBox.setFont(font)
        self.PointUsedBox.setObjectName("PointUsedBox")
        self.horizontalLayout_4.addWidget(self.PointUsedBox)
        self.YourSelection = QtWidgets.QLabel(self.centralwidget)
        self.YourSelection.setGeometry(QtCore.QRect(10, 10, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setBold(False)
        font.setWeight(50)
        self.YourSelection.setFont(font)
        self.YourSelection.setObjectName("YourSelection")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 69, 821, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 140, 821, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 25))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.NewTeam = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.NewTeam.setFont(font)
        self.NewTeam.setObjectName("NewTeam")
        self.OpenTeam = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.OpenTeam.setFont(font)
        self.OpenTeam.setObjectName("OpenTeam")
        self.SaveTeam = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.SaveTeam.setFont(font)
        self.SaveTeam.setObjectName("SaveTeam")
        self.EvaluateTeam = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.EvaluateTeam.setFont(font)
        self.EvaluateTeam.setObjectName("EvaluateTeam")
        self.menuManage_Teams.addAction(self.NewTeam)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.OpenTeam)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.SaveTeam)
        self.menuManage_Teams.addSeparator()
        self.menuManage_Teams.addAction(self.EvaluateTeam)
        self.menuManage_Teams.addSeparator()
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.list1, self.list2)
        MainWindow.setTabOrder(self.list2, self.bat)
        MainWindow.setTabOrder(self.bat, self.bowl)
        MainWindow.setTabOrder(self.bowl, self.AR)
        MainWindow.setTabOrder(self.AR, self.wk)

        #self.create_screen.PushButton.clicked.connect(self.show_teamname)
        self.bat.clicked.connect(self.show_names)
        self.bowl.clicked.connect(self.show_names)
        self.AR.clicked.connect(self.show_names)
        self.wk.clicked.connect(self.show_names)
        self.list1.doubleClicked.connect(self.take_name)
        self.list2.doubleClicked.connect(self.remove_name)
        self.NewTeam.triggered.connect(self.create_team)
        self.openTeam.triggered.connect(self.open_team)
        self.SaveTeam.triggered.connect(self.save_team)
        self.EvaluateTeam.triggered.connect(self.evaluate_team)


    def show_names(self):
        if self.bat.isChecked():
            self.list1.clear()
            curfantasy.execute('select Player from Players where type = "BAT"')
            bats_data = curfantasy.fetchall()

            for data in bats_data:
                self.list1.addItem(data[0])
        if self.bowl.isChecked():
            self.list1.clear()
            curfantasy.execute('select Player from Players where type = "BWL"')
            bowl_data = curfantasy.fetchall()

            for data in bowl_data:
                self.list1.addItem(data[0])
        if self.AR.isChecked():
            self.list1.clear()
            curfantasy.execute('select Player from Players where type = "AR"')
            AR_data = curfantasy.fetchall()

            for data in AR_data:
                self.list1.addItem(data[0])
        if self.wk.isChecked():
            self.list1.clear()
            curfantasy.execute('select Player from Players where type = "WK"')
            wk_data = curfantasy.fetchall()

            for data in wk_data:
                self.list1.addItem(data[0])
        

    def show_points(self):
        curfantasy.execute('select SUM(Points) from Players')
        Points = curfantasy.fetchall()
        self.PointsAvailableBox.setText(str(Points[0][0]))

    def take_name(self):
        if self.wk.isChecked() and self.max_WK is not 0 or self.bat.isChecked() or self.bowl.isChecked() or self.AR.isChecked():
            item = self.list1.takeItem(self.list1.currentRow())
            self.list2.addItem(item)
            item = item.text()
            curfantasy.execute("select Points from Players where Players = '" + item + "';")
            play_pt = curfantasy.fetchall()
            actual_pt = self.PointsAvailableBox.text()
            actual_pt = int(actual_pt) - int(play_pt[0][0])
            self.PointsAvailableBox.setText(str(actual_pt))
            added_pt = self.PointusedBox.text()
            add_pt = int(added_pt) + int(play_pt[0][0])
            self.PointUsedBox.setText(str(add_pt))
        else:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("You cannot select more than one wickerkeeper")
            msg.exec_()

        if self.bat.isChecked():
            bat_count = self.batsman_2.text()
            bat_count = int(bat_count)-1
            self.batsman_2.setText(str(bat_count))
        elif self.bowl.isChecked():
            bowl_count = self.Bowler_2.text()
            bowl_count = int(bowl_count)-1
            self.Bowler_2.setText(str(bowl_count))
        elif self.AR.isChecked():
            AR_count = self.AllRounder_2.text()
            AR_count = int(AR_count)-1
            self.AllRounder_2.setText(str(AR_count))
        else:
            wk_count = self.WicketKeeper_2.text()
            wk_count = int(wk_count)-1
            self.WicketKeeper_2.setText(str(wk_count))
    

    def remove_name(self):
        item= self.list2.takeItem(self.currentRow())
        curfantasy.execute("select Ctg from Stats where Player = '" + item + "';")
        type_data = curfantasy.fetchall()
        if self.bat.isChecked() and type_data[0][0] == 'Batsman':
            self.list1.addItem(item)
        elif self.bowl.isChecked() and type_data[0][0] == 'Bowler':
            self.list1.addItem(item)
        elif self.AR.isChecked() and type_data[0][0] == 'AllRounder':
            self.list1.addItem(item)
        elif self.wk.isChecked() and type_data[0][0] == 'WicketKeeper':
            self.list1.addItem(item)
            item = item.text()
            curfantasy.execute("select Points from Players where Player = '" + item + "';")
            play_pt = curfantasy.fetchall()
            actual_pt = self.PointUsedBox.text()
            actual_pt = int(actual_pt) - int(play_pt[0][0])
            self.PointUsedBox.setText(str(actual_pt))
            added_pt = self.PointAvailableBox.text()
            add_pt = int(added_pt) + int(play_pt[0][0])
            self.PointAvailableBox.setText(str(add_pt))

    def create_team(self):
        self.create_team.show()

    def open_team(self):
        self.open_team = QtWidgets.QMainWindow()
        self,open_screen = OpenTeam()
        self.open_screen.setupUi(self.open_team)
        self.open_team.show()

    def evaluate_team(self):
        self.evaluate_team = QtWidgets.QMainWindow()
        self.evaluate_screen = EvaluateTeam()
        self.evaluate_screen.setupUi(self.evaluate_team)
        self.evaluate_team.show()

    def show_teamname(self):
        self.bat.setEnabled(True)
        self.bowl.setEnabled(True)
        self.AR.setEnabled(True)
        self.wk.setEnabled(True)
        curfantasy.execute('select sum(Points) from Players')
        Points = curfantasy.fetchall()
        self.PointAvailableBox.setText(str(points[0][0]))
        self.PointUsedBox.setText(str('0'))
        curfantasy.execute('select count(Player) from Players where Ctg = "BAT"')
        bats_count = curfantasy.fetchone()
        self.batsman_2.setText(str(bats_count[0]))
        curfantasy.execute('select count(Player) from Players where Ctg = "BWL"')
        bowl_count = cur.fetchone()
        self.Bowlers_2.setText(str(bowl_count[0]))
        curfantasy.execute('select count(Player) from Players where Ctg = "AR"')
        all_count = cur.fetchone()
        self.AllRounders_2.setText(str(all_count[0]))
        cur.execute('select count(Player) from Players where Ctg = "WK"')
        wicket_count = cur.fetchone()
        self.WicketKeeper_2.setText(str(wicket_count[0]))
        TeamName = self.create_screen.lineEdit.text()
        self.TeamNameBox.setText(str(TeamName))

    def save_team(self):
        team_list = []
        team_name = self.TeamNameBox.text()
        curfantasy.execute("select Matches from Stats where Player ='" + team_name + "'")
        data = curfantasy.fetchall()
        if len(data) is not 0:
            match = data[len(data)-1][0]
            a = match.split(match[len(match)-1])
            b = match.split('Matches')
            b[1] = int(b[1])+1
            matches = a[0]+str(b[1])
        else:
            matches = 'Matches1'
        for item in range(self.list2.count()):
            team_list.append(self.list2.item(item).text())
        for item in team_list:
            curfantasy.execute("select Points from Players where Player = '" + item + "';")
            player_pt = cur.fetchall()
            #curfantasy.execute('INSERT INTO Team VALUES (?,?,?,?)', (team_name, item, player_pt[0][0], matches))
            connect.commit()
    

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bat.setText(_translate("MainWindow", "BAT"))
        self.bowl.setText(_translate("MainWindow", "BOWL"))
        self.AR.setText(_translate("MainWindow", "AR"))
        self.wk.setText(_translate("MainWindow", "WK"))
        self.batsman_1.setText(_translate("MainWindow", "Batsman (BAT)"))
        self.batsman_2.setText(_translate("MainWindow", "##"))
        self.Bowler_1.setText(_translate("MainWindow", "Bowler (BOWL)"))
        self.Bowler_2.setText(_translate("MainWindow", "##"))
        self.AllRounder_1.setText(_translate("MainWindow", "AllRounder (AR)"))
        self.AllRounder_2.setText(_translate("MainWindow", "##"))
        self.WicketKeeper_1.setText(_translate("MainWindow", "WicketKeeper(WK)"))
        self.WicketKeeper_2.setText(_translate("MainWindow", "##"))
        self.PointsAvailableText.setText(_translate("MainWindow", "Points Available"))
        self.PointsAvailableBox.setText(_translate("MainWindow", "##"))
        self.TeamNameText.setText(_translate("MainWindow", "Team Name"))
        self.TeamNameBox.setText(_translate("MainWindow", "##"))
        self.PointUsedText.setText(_translate("MainWindow", "Point Used"))
        self.PointUsedBox.setText(_translate("MainWindow", "##"))
        self.YourSelection.setText(_translate("MainWindow", "Your Selection"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.NewTeam.setText(_translate("MainWindow", "NewTeam"))
        self.OpenTeam.setText(_translate("MainWindow", "OpenTeam"))
        self.SaveTeam.setText(_translate("MainWindow", "SaveTeam"))
        self.EvaluateTeam.setText(_translate("MainWindow", "EvaluateTeam"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
